/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package manager.ui;

import java.awt.Color;

/**
 *
 * @author Dell
 */
public class ButtonPanel extends javax.swing.JPanel {
    private Color backgoundColor;
    private Color foregoundColor;
    private Color defaultBackgoundColor;
    private Color defaultForegoundColor;
    /**
     * Creates new form ButtonPanel
     */
    public ButtonPanel() {
        initComponents();
    }
    
    public ButtonPanel(Color backgoundColor, Color foregoundColor) {
        this.backgoundColor = backgoundColor;
        this.foregoundColor = foregoundColor;
        initComponents();
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonPanelMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonPanelMouseExited(evt);
            }

        });
    }
    
    public void buttonPanelMouseEntered(java.awt.event.MouseEvent evt) {
        defaultBackgoundColor = getBackground();
        defaultForegoundColor = getForeground();
        if(backgoundColor == null) {
            setBackground(defaultBackgoundColor);
        } else {
            setBackground(backgoundColor);
        } 
        
        if(foregoundColor == null) {
            setForeground(defaultForegoundColor);
        } else {
            setForeground(foregoundColor);
        } 
    }
    
    public void buttonPanelMouseExited(java.awt.event.MouseEvent evt) {
        setBackground(defaultBackgoundColor);
        setForeground(defaultForegoundColor);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(42, 42));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
