/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package manager.ui;

import manager.ui.admin.*;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JFrame;
import manager.control.InformationControl;
import manager.ui.LoginUI;

/**
 *
 * @author Dell
 */
public class StudentMenu extends javax.swing.JFrame {
    private String userName;
    private final InformationControl informationControl;
    /**
     * Creates new form MainMenu
     */   
    
    public StudentMenu(String userName){
        this.userName = userName;
        informationControl = new InformationControl(userName);
        initComponents();
        informationTab.showInformation();
        setResizable(true);
        helloLabel.setText("<html>Xin chào bạn <b>" + userName + "</b></html>");
        resetVisible();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        titlePanel = new javax.swing.JPanel();
        helloLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        helpLabel = new manager.ui.ButtonLabel(new java.awt.Color(204,204,255), new java.awt.Color(54,33,89));
        minimizeLabel = new manager.ui.ButtonLabel(new java.awt.Color(204,204,255), new java.awt.Color(54,33,89));
        exitLabel = new manager.ui.ButtonLabel(new java.awt.Color(242,38,19), Color.white);
        logoutLabel = new javax.swing.JLabel();
        sidePanel = new javax.swing.JPanel();
        sis = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        informationPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        curriculumPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        registerPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        transcriptPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        searchPanel = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        mainLayeredPane = new javax.swing.JLayeredPane();
        menuInformation = new javax.swing.JPanel();
        goInformationTab = new manager.ui.ButtonPanel(new java.awt.Color(70,53,89), null);
        iconInfoButton = new javax.swing.JLabel();
        textInfoButton = new javax.swing.JLabel();
        goChangePassTab = new manager.ui.ButtonPanel(new java.awt.Color(70,53,89), null);
        iconChangePassButton = new javax.swing.JLabel();
        textChangePassButton = new javax.swing.JLabel();
        tmpInformation = new javax.swing.JLabel();
        menuCurriculum = new javax.swing.JPanel();
        goModuleListTab = new manager.ui.ButtonPanel(new java.awt.Color(70,53,89), null);
        iconModuleListButton = new javax.swing.JLabel();
        textModuleListButton = new javax.swing.JLabel();
        tmpCurriculum1 = new javax.swing.JLabel();
        tmpCurriculum2 = new javax.swing.JLabel();
        menuRegister = new javax.swing.JPanel();
        goRegisterModuleTab = new manager.ui.ButtonPanel(new java.awt.Color(70,53,89), null);
        iconRegisterModuleButton = new javax.swing.JLabel();
        textRegisterModuleButton = new javax.swing.JLabel();
        tmpRegisterModule1 = new javax.swing.JLabel();
        tmpRegisterModule2 = new javax.swing.JLabel();
        menuTranscipt = new javax.swing.JPanel();
        goPersonalTranscriptTab = new manager.ui.ButtonPanel(new java.awt.Color(70,53,89), null);
        iconPersonalTranscriptButton = new javax.swing.JLabel();
        textPersonalTranscriptButton = new javax.swing.JLabel();
        tmpTranscript1 = new javax.swing.JLabel();
        tmpTranscript2 = new javax.swing.JLabel();
        menuSearch = new javax.swing.JPanel();
        goClassListTab = new manager.ui.ButtonPanel(new java.awt.Color(70,53,89), null);
        iconClassListButton = new javax.swing.JLabel();
        textClassListButton = new javax.swing.JLabel();
        tmpSearch1 = new javax.swing.JLabel();
        tmpSearch2 = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        information = new javax.swing.JPanel();
        informationTab = new manager.ui.InformationPanel(userName);
        changePassTab = new manager.ui.ChangePassWordPanel(userName);
        curriculum = new javax.swing.JPanel();
        moduleList = new manager.ui.ModuleListPanel();
        register = new javax.swing.JPanel();
        registerModuleTab = new manager.ui.RegisterModulePanel(userName);
        transcript = new javax.swing.JPanel();
        personalTranscriptTab = new manager.ui.AcademicTranscriptPanel(userName);
        search = new javax.swing.JPanel();
        classListTab = new manager.ui.ClassListPanel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);

        titlePanel.setBackground(new java.awt.Color(54, 33, 89));
        titlePanel.setPreferredSize(new java.awt.Dimension(1020, 56));

        helloLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        helloLabel.setForeground(new java.awt.Color(255, 255, 255));
        helloLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jPanel1.setBackground(new java.awt.Color(54, 33, 89));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        helpLabel.setBackground(new java.awt.Color(54, 33, 89));
        helpLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        helpLabel.setForeground(new java.awt.Color(204, 204, 255));
        helpLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        helpLabel.setText("?");
        helpLabel.setToolTipText("Help");
        helpLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                helpLabelMouseClicked(evt);
            }
        });
        jPanel1.add(helpLabel);

        minimizeLabel.setBackground(new java.awt.Color(54, 33, 89));
        minimizeLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        minimizeLabel.setForeground(new java.awt.Color(204, 204, 255));
        minimizeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimizeLabel.setText("_");
        minimizeLabel.setToolTipText("Minimize");
        minimizeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeLabelMouseClicked(evt);
            }
        });
        jPanel1.add(minimizeLabel);

        exitLabel.setBackground(new java.awt.Color(54, 33, 89));
        exitLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        exitLabel.setForeground(new java.awt.Color(204, 204, 255));
        exitLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitLabel.setText("X");
        exitLabel.setToolTipText("Quit");
        exitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabelMouseClicked(evt);
            }
        });
        jPanel1.add(exitLabel);

        logoutLabel.setBackground(new java.awt.Color(54, 33, 89));
        logoutLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoutLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/white-logout.png"))); // NOI18N
        logoutLabel.setOpaque(true);
        logoutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutLabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logoutLabelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addContainerGap(726, Short.MAX_VALUE)
                .addComponent(helloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logoutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(helloLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoutLabel, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        sidePanel.setBackground(new java.awt.Color(54, 33, 89));
        sidePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(85, 55, 118)));

        sis.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        sis.setForeground(new java.awt.Color(204, 204, 204));
        sis.setText("SIS");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logbk-40.jpg"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(54, 33, 89));
        jPanel2.setLayout(new java.awt.GridLayout(5, 1));

        informationPanel.setBackground(new java.awt.Color(85, 55, 118));
        informationPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        informationPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                informationPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                informationPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                informationPanelMousePressed(evt);
            }
        });
        informationPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 25, 12));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/menu/information.png"))); // NOI18N
        informationPanel.add(jLabel1);

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Thông tin cá nhân");
        informationPanel.add(jLabel3);

        jPanel2.add(informationPanel);

        curriculumPanel.setBackground(new java.awt.Color(64, 43, 100));
        curriculumPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        curriculumPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                curriculumPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                curriculumPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                curriculumPanelMousePressed(evt);
            }
        });
        curriculumPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 25, 12));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/menu/curriculum.png"))); // NOI18N
        curriculumPanel.add(jLabel4);

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Chương trình đào tạo");
        curriculumPanel.add(jLabel5);

        jPanel2.add(curriculumPanel);

        registerPanel.setBackground(new java.awt.Color(64, 43, 100));
        registerPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registerPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registerPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                registerPanelMousePressed(evt);
            }
        });
        registerPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 25, 12));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/menu/register.png"))); // NOI18N
        registerPanel.add(jLabel9);

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Đăng ký học tập");
        registerPanel.add(jLabel10);

        jPanel2.add(registerPanel);

        transcriptPanel.setBackground(new java.awt.Color(64, 43, 100));
        transcriptPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        transcriptPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                transcriptPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                transcriptPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                transcriptPanelMousePressed(evt);
            }
        });
        transcriptPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 25, 12));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/menu/transcipt.png"))); // NOI18N
        transcriptPanel.add(jLabel11);

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("Kết quả học tập");
        transcriptPanel.add(jLabel13);

        jPanel2.add(transcriptPanel);

        searchPanel.setBackground(new java.awt.Color(64, 43, 100));
        searchPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                searchPanelMousePressed(evt);
            }
        });
        searchPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 25, 12));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/menu/search.png"))); // NOI18N
        searchPanel.add(jLabel14);

        jLabel15.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("Tra cứu");
        searchPanel.add(jLabel15);

        jPanel2.add(searchPanel);

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel12))
                    .addComponent(sis))
                .addGap(95, 95, 95))
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(sis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 105, Short.MAX_VALUE))
        );

        mainLayeredPane.setPreferredSize(new java.awt.Dimension(1020, 565));

        menuInformation.setBackground(new java.awt.Color(255, 255, 255));
        menuInformation.setPreferredSize(new java.awt.Dimension(150, 566));
        menuInformation.setLayout(new java.awt.GridLayout(3, 1));

        goInformationTab.setBackground(new java.awt.Color(85, 55, 118));
        goInformationTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                goInformationTabMousePressed(evt);
            }
        });
        goInformationTab.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 30));

        iconInfoButton.setBackground(new java.awt.Color(255, 255, 255));
        iconInfoButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconInfoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/information/information.png"))); // NOI18N
        iconInfoButton.setMaximumSize(new java.awt.Dimension(64, 64));
        iconInfoButton.setMinimumSize(new java.awt.Dimension(64, 64));
        iconInfoButton.setPreferredSize(new java.awt.Dimension(64, 64));
        goInformationTab.add(iconInfoButton);

        textInfoButton.setBackground(new java.awt.Color(255, 255, 255));
        textInfoButton.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        textInfoButton.setForeground(new java.awt.Color(255, 255, 255));
        textInfoButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textInfoButton.setText("Thêm tài khoản");
        goInformationTab.add(textInfoButton);

        menuInformation.add(goInformationTab);

        goChangePassTab.setBackground(new java.awt.Color(85, 55, 118));
        goChangePassTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                goChangePassTabMousePressed(evt);
            }
        });
        goChangePassTab.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 30));

        iconChangePassButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconChangePassButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/information/password.png"))); // NOI18N
        goChangePassTab.add(iconChangePassButton);

        textChangePassButton.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        textChangePassButton.setForeground(new java.awt.Color(255, 255, 255));
        textChangePassButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textChangePassButton.setText("Chỉnh sửa tài khoản");
        goChangePassTab.add(textChangePassButton);

        menuInformation.add(goChangePassTab);

        tmpInformation.setBackground(new java.awt.Color(85, 55, 118));
        tmpInformation.setOpaque(true);
        menuInformation.add(tmpInformation);

        menuCurriculum.setBackground(new java.awt.Color(85, 55, 118));
        menuCurriculum.setLayout(new java.awt.GridLayout(3, 1));

        goModuleListTab.setBackground(new java.awt.Color(85, 55, 118));
        goModuleListTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                goModuleListTabMousePressed(evt);
            }
        });
        goModuleListTab.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 30));

        iconModuleListButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconModuleListButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/curriculumn/list.png"))); // NOI18N
        goModuleListTab.add(iconModuleListButton);

        textModuleListButton.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        textModuleListButton.setForeground(new java.awt.Color(255, 255, 255));
        textModuleListButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textModuleListButton.setText("Danh mục học phần");
        goModuleListTab.add(textModuleListButton);

        menuCurriculum.add(goModuleListTab);

        tmpCurriculum1.setBackground(new java.awt.Color(85, 55, 118));
        tmpCurriculum1.setOpaque(true);
        menuCurriculum.add(tmpCurriculum1);

        tmpCurriculum2.setBackground(new java.awt.Color(85, 55, 118));
        tmpCurriculum2.setOpaque(true);
        menuCurriculum.add(tmpCurriculum2);

        menuRegister.setPreferredSize(new java.awt.Dimension(175, 567));
        menuRegister.setLayout(new java.awt.GridLayout(3, 1));

        goRegisterModuleTab.setBackground(new java.awt.Color(85, 55, 118));
        goRegisterModuleTab.setPreferredSize(new java.awt.Dimension(200, 102));
        goRegisterModuleTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                goRegisterModuleTabMousePressed(evt);
            }
        });
        goRegisterModuleTab.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 30));

        iconRegisterModuleButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconRegisterModuleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/register/module.png"))); // NOI18N
        goRegisterModuleTab.add(iconRegisterModuleButton);

        textRegisterModuleButton.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        textRegisterModuleButton.setForeground(new java.awt.Color(255, 255, 255));
        textRegisterModuleButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textRegisterModuleButton.setText("Đăng ký học phần");
        goRegisterModuleTab.add(textRegisterModuleButton);

        menuRegister.add(goRegisterModuleTab);

        tmpRegisterModule1.setBackground(new java.awt.Color(85, 55, 118));
        tmpRegisterModule1.setOpaque(true);
        menuRegister.add(tmpRegisterModule1);

        tmpRegisterModule2.setBackground(new java.awt.Color(85, 55, 118));
        tmpRegisterModule2.setOpaque(true);
        menuRegister.add(tmpRegisterModule2);

        menuTranscipt.setPreferredSize(new java.awt.Dimension(175, 567));
        menuTranscipt.setLayout(new java.awt.GridLayout(3, 1));

        goPersonalTranscriptTab.setBackground(new java.awt.Color(85, 55, 118));
        goPersonalTranscriptTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                goPersonalTranscriptTabMousePressed(evt);
            }
        });
        goPersonalTranscriptTab.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 30));

        iconPersonalTranscriptButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconPersonalTranscriptButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/transcript/table.png"))); // NOI18N
        goPersonalTranscriptTab.add(iconPersonalTranscriptButton);

        textPersonalTranscriptButton.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        textPersonalTranscriptButton.setForeground(new java.awt.Color(255, 255, 255));
        textPersonalTranscriptButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textPersonalTranscriptButton.setText("Bảng điểm cá nhân");
        goPersonalTranscriptTab.add(textPersonalTranscriptButton);

        menuTranscipt.add(goPersonalTranscriptTab);

        tmpTranscript1.setBackground(new java.awt.Color(85, 55, 118));
        tmpTranscript1.setOpaque(true);
        menuTranscipt.add(tmpTranscript1);

        tmpTranscript2.setBackground(new java.awt.Color(85, 55, 118));
        tmpTranscript2.setOpaque(true);
        menuTranscipt.add(tmpTranscript2);

        menuSearch.setPreferredSize(new java.awt.Dimension(175, 565));
        menuSearch.setLayout(new java.awt.GridLayout(3, 1));

        goClassListTab.setBackground(new java.awt.Color(85, 55, 118));
        goClassListTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                goClassListTabMousePressed(evt);
            }
        });
        goClassListTab.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 30));

        iconClassListButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search/class.png"))); // NOI18N
        goClassListTab.add(iconClassListButton);

        textClassListButton.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        textClassListButton.setForeground(new java.awt.Color(255, 255, 255));
        textClassListButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textClassListButton.setText("Danh sách lớp SV");
        goClassListTab.add(textClassListButton);

        menuSearch.add(goClassListTab);

        tmpSearch1.setBackground(new java.awt.Color(85, 55, 118));
        tmpSearch1.setOpaque(true);
        menuSearch.add(tmpSearch1);

        tmpSearch2.setBackground(new java.awt.Color(85, 55, 118));
        tmpSearch2.setOpaque(true);
        menuSearch.add(tmpSearch2);

        mainPanel.setMinimumSize(new java.awt.Dimension(1020, 1393));
        mainPanel.setPreferredSize(new java.awt.Dimension(1020, 565));
        mainPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mainPanelMousePressed(evt);
            }
        });
        mainPanel.setLayout(new java.awt.CardLayout());

        information.setBackground(new java.awt.Color(255, 255, 255));
        information.setLayout(new java.awt.CardLayout());
        information.add(informationTab, "informationCard");
        information.add(changePassTab, "changePassCard");

        mainPanel.add(information, "informationCard");

        curriculum.setLayout(new java.awt.CardLayout());
        curriculum.add(moduleList, "moduleListCard");

        mainPanel.add(curriculum, "curriculumCard");

        register.setLayout(new java.awt.CardLayout());
        register.add(registerModuleTab, "registerModuleCard");

        mainPanel.add(register, "registerCard");

        transcript.setLayout(new java.awt.CardLayout());
        transcript.add(personalTranscriptTab, "academyTranscriptCard");

        mainPanel.add(transcript, "transcriptCard");

        search.setLayout(new java.awt.CardLayout());
        search.add(classListTab, "classListCard");

        mainPanel.add(search, "searchCard");

        mainLayeredPane.setLayer(menuInformation, javax.swing.JLayeredPane.MODAL_LAYER);
        mainLayeredPane.setLayer(menuCurriculum, javax.swing.JLayeredPane.MODAL_LAYER);
        mainLayeredPane.setLayer(menuRegister, javax.swing.JLayeredPane.MODAL_LAYER);
        mainLayeredPane.setLayer(menuTranscipt, javax.swing.JLayeredPane.MODAL_LAYER);
        mainLayeredPane.setLayer(menuSearch, javax.swing.JLayeredPane.MODAL_LAYER);
        mainLayeredPane.setLayer(mainPanel, javax.swing.JLayeredPane.MODAL_LAYER);

        javax.swing.GroupLayout mainLayeredPaneLayout = new javax.swing.GroupLayout(mainLayeredPane);
        mainLayeredPane.setLayout(mainLayeredPaneLayout);
        mainLayeredPaneLayout.setHorizontalGroup(
            mainLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(mainLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainLayeredPaneLayout.createSequentialGroup()
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1043, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(mainLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainLayeredPaneLayout.createSequentialGroup()
                    .addComponent(menuInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 877, Short.MAX_VALUE)))
            .addGroup(mainLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainLayeredPaneLayout.createSequentialGroup()
                    .addComponent(menuCurriculum, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 877, Short.MAX_VALUE)))
            .addGroup(mainLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainLayeredPaneLayout.createSequentialGroup()
                    .addComponent(menuRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 877, Short.MAX_VALUE)))
            .addGroup(mainLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainLayeredPaneLayout.createSequentialGroup()
                    .addComponent(menuTranscipt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 877, Short.MAX_VALUE)))
            .addGroup(mainLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainLayeredPaneLayout.createSequentialGroup()
                    .addComponent(menuSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 878, Short.MAX_VALUE)))
        );
        mainLayeredPaneLayout.setVerticalGroup(
            mainLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(mainLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainLayeredPaneLayout.createSequentialGroup()
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 22, Short.MAX_VALUE)))
            .addGroup(mainLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainLayeredPaneLayout.createSequentialGroup()
                    .addComponent(menuInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(mainLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainLayeredPaneLayout.createSequentialGroup()
                    .addComponent(menuCurriculum, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 22, Short.MAX_VALUE)))
            .addGroup(mainLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainLayeredPaneLayout.createSequentialGroup()
                    .addComponent(menuRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 22, Short.MAX_VALUE)))
            .addGroup(mainLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainLayeredPaneLayout.createSequentialGroup()
                    .addComponent(menuTranscipt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 22, Short.MAX_VALUE)))
            .addGroup(mainLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainLayeredPaneLayout.createSequentialGroup()
                    .addComponent(menuSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1043, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 274, Short.MAX_VALUE)
                    .addComponent(mainLayeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1043, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 56, Short.MAX_VALUE)
                    .addComponent(mainLayeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseClicked
        super.dispose();
        System.exit(0);
    }//GEN-LAST:event_exitLabelMouseClicked

    private void minimizeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLabelMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeLabelMouseClicked

    private void helpLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpLabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_helpLabelMouseClicked

    private void resetVisible() {
        if(menuInformation.isVisible()) {
            menuInformation.setVisible(false);
        }
        if(menuCurriculum.isVisible()) {
            menuCurriculum.setVisible(false);
        }
        if(menuRegister.isVisible()) {
            menuRegister.setVisible(false);
        }
        if(menuTranscipt.isVisible()) {
            menuTranscipt.setVisible(false);
        }
        if(menuSearch.isVisible()) {
            menuSearch.setVisible(false);
        }
    }
    
    private void informationPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_informationPanelMousePressed
        mainLayeredPane.moveToFront(menuInformation);
        resetColor();
        informationPanel.setBackground(new java.awt.Color(85,55,118));
        
        if(menuInformation.isVisible() == false) {
            resetVisible();
            menuInformation.setVisible(true);
        } else {
            resetVisible(); 
        }
        //((CardLayout)mainPanel.getLayout()).show(mainPanel, "accountManagerCard");
        //((CardLayout)accountManager.getLayout()).show(accountManager, "menuAccountCard");
        
    }//GEN-LAST:event_informationPanelMousePressed

    private void curriculumPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_curriculumPanelMousePressed
        mainLayeredPane.moveToFront(menuCurriculum);
        resetColor();
        curriculumPanel.setBackground(new java.awt.Color(85,55,118));
        
        if(menuCurriculum.isVisible() == false) {
            resetVisible();
            menuCurriculum.setVisible(true);
        } else {
            resetVisible(); 
        }
        
        //((CardLayout)mainPanel.getLayout()).show(mainPanel, "curriculumCard");
        //((CardLayout)moduleManager.getLayout()).show(moduleManager, "menuCurriculumnCard");
    }//GEN-LAST:event_curriculumPanelMousePressed

    private void informationPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_informationPanelMouseEntered
        java.awt.Color color = new java.awt.Color(85,55,118);
        if(informationPanel.getBackground().getRGB() != color.getRGB()) {
            informationPanel.setBackground(new java.awt.Color(52,35,82));
        } 
    }//GEN-LAST:event_informationPanelMouseEntered

    private void informationPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_informationPanelMouseExited
        java.awt.Color color = new java.awt.Color(85,55,118);
        if(informationPanel.getBackground().getRGB() != color.getRGB()) {
            informationPanel.setBackground(new java.awt.Color(64,43,100));
        } 
    }//GEN-LAST:event_informationPanelMouseExited

    private void curriculumPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_curriculumPanelMouseEntered
        java.awt.Color color = new java.awt.Color(85,55,118);
        if(curriculumPanel.getBackground().getRGB() != color.getRGB()) {
            curriculumPanel.setBackground(new java.awt.Color(52,35,82));
        } 
    }//GEN-LAST:event_curriculumPanelMouseEntered

    private void curriculumPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_curriculumPanelMouseExited
        java.awt.Color color = new java.awt.Color(85,55,118);
        if(curriculumPanel.getBackground().getRGB() != color.getRGB()) {
            curriculumPanel.setBackground(new java.awt.Color(64,43,100));
        } 
    }//GEN-LAST:event_curriculumPanelMouseExited

    private void logoutLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabelMouseEntered
        logoutLabel.setBackground(new java.awt.Color(242,38,19));
        logoutLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/white-logout.png")));
    }//GEN-LAST:event_logoutLabelMouseEntered

    private void logoutLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabelMouseExited
        logoutLabel.setBackground(new java.awt.Color(54,33,89));
    }//GEN-LAST:event_logoutLabelMouseExited

    private void logoutLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabelMousePressed
        super.dispose();
        LoginUI.main(null);
    }//GEN-LAST:event_logoutLabelMousePressed

    private void goInformationTabMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goInformationTabMousePressed
        resetVisible();
        ((CardLayout)mainPanel.getLayout()).show(mainPanel, "informationCard");
        ((CardLayout)information.getLayout()).show(information, "informationCard");
        informationTab.reset();
    }//GEN-LAST:event_goInformationTabMousePressed

    private void goChangePassTabMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goChangePassTabMousePressed
        resetVisible();
        ((CardLayout)mainPanel.getLayout()).show(mainPanel, "informationCard");
        ((CardLayout)information.getLayout()).show(information, "changePassCard");
        changePassTab.reset();
    }//GEN-LAST:event_goChangePassTabMousePressed

    private void goModuleListTabMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goModuleListTabMousePressed
        resetVisible();
        moduleList.reset();
        moduleList.addFacultyComboBox();
        moduleList.initTable();
        ((CardLayout)mainPanel.getLayout()).show(mainPanel, "curriculumCard");
        ((CardLayout)curriculum.getLayout()).show(curriculum, "moduleListCard");
    }//GEN-LAST:event_goModuleListTabMousePressed

    private void mainPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainPanelMousePressed
        resetVisible();
    }//GEN-LAST:event_mainPanelMousePressed

    private void registerPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerPanelMouseEntered
        java.awt.Color color = new java.awt.Color(85,55,118);
        if(registerPanel.getBackground().getRGB() != color.getRGB()) {
            registerPanel.setBackground(new java.awt.Color(52,35,82));
        }
    }//GEN-LAST:event_registerPanelMouseEntered

    private void registerPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerPanelMouseExited
        java.awt.Color color = new java.awt.Color(85,55,118);
        if(registerPanel.getBackground().getRGB() != color.getRGB()) {
            registerPanel.setBackground(new java.awt.Color(64,43,100));
        }
    }//GEN-LAST:event_registerPanelMouseExited

    private void registerPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerPanelMousePressed
        mainLayeredPane.moveToFront(menuRegister);
        resetColor();
        registerPanel.setBackground(new java.awt.Color(85,55,118));
        
        if(menuRegister.isVisible() == false) {
            resetVisible();
            menuRegister.setVisible(true);
        } else {
            resetVisible(); 
        }
    }//GEN-LAST:event_registerPanelMousePressed

    private void transcriptPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transcriptPanelMouseEntered
        java.awt.Color color = new java.awt.Color(85,55,118);
        if(transcriptPanel.getBackground().getRGB() != color.getRGB()) {
            transcriptPanel.setBackground(new java.awt.Color(52,35,82));
        }
    }//GEN-LAST:event_transcriptPanelMouseEntered

    private void transcriptPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transcriptPanelMouseExited
        java.awt.Color color = new java.awt.Color(85,55,118);
        if(transcriptPanel.getBackground().getRGB() != color.getRGB()) {
            transcriptPanel.setBackground(new java.awt.Color(64,43,100));
        }
    }//GEN-LAST:event_transcriptPanelMouseExited

    private void transcriptPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transcriptPanelMousePressed
        mainLayeredPane.moveToFront(menuTranscipt);
        resetColor();
        transcriptPanel.setBackground(new java.awt.Color(85,55,118));
        
        if(menuTranscipt.isVisible() == false) {
            resetVisible();
            menuTranscipt.setVisible(true);
        } else {
            resetVisible(); 
        }
    }//GEN-LAST:event_transcriptPanelMousePressed

    private void searchPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchPanelMouseEntered
        java.awt.Color color = new java.awt.Color(85,55,118);
        if(searchPanel.getBackground().getRGB() != color.getRGB()) {
            searchPanel.setBackground(new java.awt.Color(52,35,82));
        }
    }//GEN-LAST:event_searchPanelMouseEntered

    private void searchPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchPanelMouseExited
        java.awt.Color color = new java.awt.Color(85,55,118);
        if(searchPanel.getBackground().getRGB() != color.getRGB()) {
            searchPanel.setBackground(new java.awt.Color(64,43,100));
        }
    }//GEN-LAST:event_searchPanelMouseExited

    private void searchPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchPanelMousePressed
        mainLayeredPane.moveToFront(menuSearch);
        resetColor();
        searchPanel.setBackground(new java.awt.Color(85,55,118));
        
        if(menuSearch.isVisible() == false) {
            resetVisible();
            menuSearch.setVisible(true);
        } else {
            resetVisible(); 
        }
    }//GEN-LAST:event_searchPanelMousePressed

    private void goRegisterModuleTabMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goRegisterModuleTabMousePressed
        resetVisible();
        ((CardLayout)mainPanel.getLayout()).show(mainPanel, "registerCard");
        ((CardLayout)register.getLayout()).show(register, "registerModuleCard");
        registerModuleTab.reset();
        registerModuleTab.addSemesterList();
    }//GEN-LAST:event_goRegisterModuleTabMousePressed

    private void goPersonalTranscriptTabMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goPersonalTranscriptTabMousePressed
        resetVisible();
        ((CardLayout)mainPanel.getLayout()).show(mainPanel, "transcriptCard");
        ((CardLayout)transcript.getLayout()).show(transcript, "academyTranscriptCard");
    }//GEN-LAST:event_goPersonalTranscriptTabMousePressed

    private void goClassListTabMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goClassListTabMousePressed
        resetVisible();
        classListTab.reset();
        classListTab.addFacultyComboBox();
        classListTab.addTermComboBox();
        ((CardLayout)mainPanel.getLayout()).show(mainPanel, "searchCard");
        ((CardLayout)search.getLayout()).show(search, "classListCard");
    }//GEN-LAST:event_goClassListTabMousePressed

    private void resetColor() {
        informationPanel.setBackground(new java.awt.Color(64,43,100));
        curriculumPanel.setBackground(new java.awt.Color(64,43,100));
        registerPanel.setBackground(new java.awt.Color(64,43,100));
        transcriptPanel.setBackground(new java.awt.Color(64,43,100));
        searchPanel.setBackground(new java.awt.Color(64,43,100));
    }
    /**
     * @param userName
     */
    public static void main(String userName) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new StudentMenu(userName).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private manager.ui.ChangePassWordPanel changePassTab;
    private manager.ui.ClassListPanel classListTab;
    private javax.swing.JPanel curriculum;
    private javax.swing.JPanel curriculumPanel;
    private javax.swing.JLabel exitLabel;
    private manager.ui.ButtonPanel goChangePassTab;
    private manager.ui.ButtonPanel goClassListTab;
    private manager.ui.ButtonPanel goInformationTab;
    private manager.ui.ButtonPanel goModuleListTab;
    private manager.ui.ButtonPanel goPersonalTranscriptTab;
    private manager.ui.ButtonPanel goRegisterModuleTab;
    private javax.swing.JLabel helloLabel;
    private javax.swing.JLabel helpLabel;
    private javax.swing.JLabel iconChangePassButton;
    private javax.swing.JLabel iconClassListButton;
    private javax.swing.JLabel iconInfoButton;
    private javax.swing.JLabel iconModuleListButton;
    private javax.swing.JLabel iconPersonalTranscriptButton;
    private javax.swing.JLabel iconRegisterModuleButton;
    private javax.swing.JPanel information;
    private javax.swing.JPanel informationPanel;
    private manager.ui.InformationPanel informationTab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel logoutLabel;
    private javax.swing.JLayeredPane mainLayeredPane;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel menuCurriculum;
    private javax.swing.JPanel menuInformation;
    private javax.swing.JPanel menuRegister;
    private javax.swing.JPanel menuSearch;
    private javax.swing.JPanel menuTranscipt;
    private javax.swing.JLabel minimizeLabel;
    private manager.ui.ModuleListPanel moduleList;
    private manager.ui.AcademicTranscriptPanel personalTranscriptTab;
    private javax.swing.JPanel register;
    private manager.ui.RegisterModulePanel registerModuleTab;
    private javax.swing.JPanel registerPanel;
    private javax.swing.JPanel search;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JLabel sis;
    private javax.swing.JLabel textChangePassButton;
    private javax.swing.JLabel textClassListButton;
    private javax.swing.JLabel textInfoButton;
    private javax.swing.JLabel textModuleListButton;
    private javax.swing.JLabel textPersonalTranscriptButton;
    private javax.swing.JLabel textRegisterModuleButton;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JLabel tmpCurriculum1;
    private javax.swing.JLabel tmpCurriculum2;
    private javax.swing.JLabel tmpInformation;
    private javax.swing.JLabel tmpRegisterModule1;
    private javax.swing.JLabel tmpRegisterModule2;
    private javax.swing.JLabel tmpSearch1;
    private javax.swing.JLabel tmpSearch2;
    private javax.swing.JLabel tmpTranscript1;
    private javax.swing.JLabel tmpTranscript2;
    private javax.swing.JPanel transcript;
    private javax.swing.JPanel transcriptPanel;
    // End of variables declaration//GEN-END:variables
}
